<?php

return [
    'Getting Started' => [
        'url' => 'docs/installation',
        'children' => [
            'Quick Start' => 'docs/quick-start',
            'CLI Reference' => 'docs/cli-reference',
            'Configuration' => 'docs/configuration',
        ],
    ],
    'Components' => [
        'url' => 'docs/components',
        'children' => [
            'Accordion' => 'docs/components/accordion',
            'Alert' => 'docs/components/alert',
            'Avatar' => 'docs/components/avatar',
            'Avatar Group' => 'docs/components/avatar-group',
            'Badge' => 'docs/components/badge',
            'Breadcrumbs' => 'docs/components/breadcrumbs',
            'Button' => 'docs/components/button',
            'Card' => 'docs/components/card',
            'Command Palette' => 'docs/components/command-palette',
            'Table' => 'docs/components/table',
            'Date Picker' => 'docs/components/date-picker',
            'Drawer' => 'docs/components/drawer',
            'Dropdown Menu' => 'docs/components/dropdown-menu',
            'Empty State' => 'docs/components/empty-state',
            'File Upload' => 'docs/components/file-upload',
            'Input' => 'docs/components/input',
            'KBD' => 'docs/components/kbd',
            'Label' => 'docs/components/label',
            'Markdown Viewer' => 'docs/components/markdown-viewer',
            'Modal' => 'docs/components/modal',
            'Popover' => 'docs/components/popover',
            'Progress Bar' => 'docs/components/progress-bar',
            'Progress Steps' => 'docs/components/progress-steps',
            'Range Slider' => 'docs/components/range-slider',
            'Rating' => 'docs/components/rating',
            'Skeleton' => 'docs/components/skeleton',
            'Sortable List' => 'docs/components/sortable-list',
            'Stat Card' => 'docs/components/stat-card',
            'Stepper' => 'docs/components/stepper',
            'Tabs' => 'docs/components/tabs',
            'Timeline' => 'docs/components/timeline',
            'Toast' => 'docs/components/toast',
            'Toggle' => 'docs/components/toggle',
            'Tooltip' => 'docs/components/tooltip',
        ],
    ],
    'Theming' => [
        'url' => 'docs/theming',
        'children' => [
            'Colors' => 'docs/design/colors',
            'Typography' => 'docs/design/typography',
            'Spacing' => 'docs/design/spacing',
        ],
    ],
];
